import { CODE_TO_ISO } from './flags'

// Localized country names keyed by flagcdn slug (ISO2 / UK nations).
const NAMES = {
  us: { de: 'USA', en: 'USA' },
  ca: { de: 'Kanada', en: 'Canada' },
  mx: { de: 'Mexiko', en: 'Mexico' },
  de: { de: 'Deutschland', en: 'Germany' },
  es: { de: 'Spanien', en: 'Spain' },
  fr: { de: 'Frankreich', en: 'France' },
  'gb-eng': { de: 'England', en: 'England' },
  'gb-sct': { de: 'Schottland', en: 'Scotland' },
  'gb-wls': { de: 'Wales', en: 'Wales' },
  pt: { de: 'Portugal', en: 'Portugal' },
  nl: { de: 'Niederlande', en: 'Netherlands' },
  it: { de: 'Italien', en: 'Italy' },
  be: { de: 'Belgien', en: 'Belgium' },
  hr: { de: 'Kroatien', en: 'Croatia' },
  ch: { de: 'Schweiz', en: 'Switzerland' },
  at: { de: 'Österreich', en: 'Austria' },
  dk: { de: 'Dänemark', en: 'Denmark' },
  pl: { de: 'Polen', en: 'Poland' },
  se: { de: 'Schweden', en: 'Sweden' },
  no: { de: 'Norwegen', en: 'Norway' },
  rs: { de: 'Serbien', en: 'Serbia' },
  tr: { de: 'Türkei', en: 'Türkiye' },
  ua: { de: 'Ukraine', en: 'Ukraine' },
  cz: { de: 'Tschechien', en: 'Czechia' },
  hu: { de: 'Ungarn', en: 'Hungary' },
  gr: { de: 'Griechenland', en: 'Greece' },
  si: { de: 'Slowenien', en: 'Slovenia' },
  sk: { de: 'Slowakei', en: 'Slovakia' },
  ro: { de: 'Rumänien', en: 'Romania' },
  br: { de: 'Brasilien', en: 'Brazil' },
  ar: { de: 'Argentinien', en: 'Argentina' },
  uy: { de: 'Uruguay', en: 'Uruguay' },
  co: { de: 'Kolumbien', en: 'Colombia' },
  ec: { de: 'Ecuador', en: 'Ecuador' },
  pe: { de: 'Peru', en: 'Peru' },
  cl: { de: 'Chile', en: 'Chile' },
  py: { de: 'Paraguay', en: 'Paraguay' },
  ve: { de: 'Venezuela', en: 'Venezuela' },
  bo: { de: 'Bolivien', en: 'Bolivia' },
  ma: { de: 'Marokko', en: 'Morocco' },
  sn: { de: 'Senegal', en: 'Senegal' },
  tn: { de: 'Tunesien', en: 'Tunisia' },
  dz: { de: 'Algerien', en: 'Algeria' },
  eg: { de: 'Ägypten', en: 'Egypt' },
  ng: { de: 'Nigeria', en: 'Nigeria' },
  cm: { de: 'Kamerun', en: 'Cameroon' },
  gh: { de: 'Ghana', en: 'Ghana' },
  ci: { de: 'Elfenbeinküste', en: 'Ivory Coast' },
  za: { de: 'Südafrika', en: 'South Africa' },
  ml: { de: 'Mali', en: 'Mali' },
  ao: { de: 'Angola', en: 'Angola' },
  cv: { de: 'Kap Verde', en: 'Cape Verde' },
  cd: { de: 'DR Kongo', en: 'DR Congo' },
  cg: { de: 'Kongo', en: 'Congo' },
  gn: { de: 'Guinea', en: 'Guinea' },
  jp: { de: 'Japan', en: 'Japan' },
  kr: { de: 'Südkorea', en: 'South Korea' },
  ir: { de: 'Iran', en: 'Iran' },
  sa: { de: 'Saudi-Arabien', en: 'Saudi Arabia' },
  au: { de: 'Australien', en: 'Australia' },
  qa: { de: 'Katar', en: 'Qatar' },
  iq: { de: 'Irak', en: 'Iraq' },
  ae: { de: 'VAE', en: 'UAE' },
  uz: { de: 'Usbekistan', en: 'Uzbekistan' },
  jo: { de: 'Jordanien', en: 'Jordan' },
  nz: { de: 'Neuseeland', en: 'New Zealand' },
  cr: { de: 'Costa Rica', en: 'Costa Rica' },
  pa: { de: 'Panama', en: 'Panama' },
  jm: { de: 'Jamaika', en: 'Jamaica' },
  hn: { de: 'Honduras', en: 'Honduras' },
  ht: { de: 'Haiti', en: 'Haiti' },
  cw: { de: 'Curaçao', en: 'Curaçao' },
  sv: { de: 'El Salvador', en: 'El Salvador' },
  gt: { de: 'Guatemala', en: 'Guatemala' },
  // Rest of UEFA
  ba: { de: 'Bosnien-Herzegowina', en: 'Bosnia & Herzegovina' },
  mk: { de: 'Nordmazedonien', en: 'North Macedonia' },
  al: { de: 'Albanien', en: 'Albania' },
  il: { de: 'Israel', en: 'Israel' },
  fi: { de: 'Finnland', en: 'Finland' },
  is: { de: 'Island', en: 'Iceland' },
  ie: { de: 'Irland', en: 'Ireland' },
  'gb-nir': { de: 'Nordirland', en: 'Northern Ireland' },
  me: { de: 'Montenegro', en: 'Montenegro' },
  xk: { de: 'Kosovo', en: 'Kosovo' },
  ge: { de: 'Georgien', en: 'Georgia' },
  am: { de: 'Armenien', en: 'Armenia' },
  az: { de: 'Aserbaidschan', en: 'Azerbaijan' },
  kz: { de: 'Kasachstan', en: 'Kazakhstan' },
  bg: { de: 'Bulgarien', en: 'Bulgaria' },
  by: { de: 'Belarus', en: 'Belarus' },
  lu: { de: 'Luxemburg', en: 'Luxembourg' },
  lt: { de: 'Litauen', en: 'Lithuania' },
  lv: { de: 'Lettland', en: 'Latvia' },
  ee: { de: 'Estland', en: 'Estonia' },
  cy: { de: 'Zypern', en: 'Cyprus' },
  mt: { de: 'Malta', en: 'Malta' },
  ad: { de: 'Andorra', en: 'Andorra' },
  fo: { de: 'Färöer', en: 'Faroe Islands' },
  gi: { de: 'Gibraltar', en: 'Gibraltar' },
  li: { de: 'Liechtenstein', en: 'Liechtenstein' },
  sm: { de: 'San Marino', en: 'San Marino' },
  md: { de: 'Moldau', en: 'Moldova' },
  // More Africa
  bf: { de: 'Burkina Faso', en: 'Burkina Faso' },
  ga: { de: 'Gabun', en: 'Gabon' },
  bj: { de: 'Benin', en: 'Benin' },
  tg: { de: 'Togo', en: 'Togo' },
  zm: { de: 'Sambia', en: 'Zambia' },
  tz: { de: 'Tansania', en: 'Tanzania' },
  ug: { de: 'Uganda', en: 'Uganda' },
  ke: { de: 'Kenia', en: 'Kenya' },
  mr: { de: 'Mauretanien', en: 'Mauritania' },
  sd: { de: 'Sudan', en: 'Sudan' },
  ly: { de: 'Libyen', en: 'Libya' },
  gq: { de: 'Äquatorialguinea', en: 'Equatorial Guinea' },
  gm: { de: 'Gambia', en: 'Gambia' },
  gw: { de: 'Guinea-Bissau', en: 'Guinea-Bissau' },
  km: { de: 'Komoren', en: 'Comoros' },
  mg: { de: 'Madagaskar', en: 'Madagascar' },
  mz: { de: 'Mosambik', en: 'Mozambique' },
  na: { de: 'Namibia', en: 'Namibia' },
  bw: { de: 'Botswana', en: 'Botswana' },
  zw: { de: 'Simbabwe', en: 'Zimbabwe' },
  sl: { de: 'Sierra Leone', en: 'Sierra Leone' },
  lr: { de: 'Liberia', en: 'Liberia' },
  ne: { de: 'Niger', en: 'Niger' },
  // More Asia
  th: { de: 'Thailand', en: 'Thailand' },
  vn: { de: 'Vietnam', en: 'Vietnam' },
  in: { de: 'Indien', en: 'India' },
  id: { de: 'Indonesien', en: 'Indonesia' },
  my: { de: 'Malaysia', en: 'Malaysia' },
  ph: { de: 'Philippinen', en: 'Philippines' },
  tj: { de: 'Tadschikistan', en: 'Tajikistan' },
  tm: { de: 'Turkmenistan', en: 'Turkmenistan' },
  kg: { de: 'Kirgisistan', en: 'Kyrgyzstan' },
  ps: { de: 'Palästina', en: 'Palestine' },
  lb: { de: 'Libanon', en: 'Lebanon' },
  sy: { de: 'Syrien', en: 'Syria' },
  kw: { de: 'Kuwait', en: 'Kuwait' },
  ye: { de: 'Jemen', en: 'Yemen' },
  hk: { de: 'Hongkong', en: 'Hong Kong' },
  bh: { de: 'Bahrain', en: 'Bahrain' },
  om: { de: 'Oman', en: 'Oman' },
  cn: { de: 'China', en: 'China' },
  kp: { de: 'Nordkorea', en: 'North Korea' },
  sg: { de: 'Singapur', en: 'Singapore' },
  mn: { de: 'Mongolei', en: 'Mongolia' },
  // More Oceania
  fj: { de: 'Fidschi', en: 'Fiji' },
  sb: { de: 'Salomonen', en: 'Solomon Islands' },
  vu: { de: 'Vanuatu', en: 'Vanuatu' },
  pg: { de: 'Papua-Neuguinea', en: 'Papua New Guinea' },
  nc: { de: 'Neukaledonien', en: 'New Caledonia' },
  pf: { de: 'Tahiti', en: 'Tahiti' },
  ck: { de: 'Cookinseln', en: 'Cook Islands' },
  ws: { de: 'Samoa', en: 'Samoa' },
  to: { de: 'Tonga', en: 'Tonga' },
  // More CONCACAF / Caribbean
  tt: { de: 'Trinidad & Tobago', en: 'Trinidad & Tobago' },
  sr: { de: 'Suriname', en: 'Suriname' },
  gy: { de: 'Guyana', en: 'Guyana' },
  ni: { de: 'Nicaragua', en: 'Nicaragua' },
  gd: { de: 'Grenada', en: 'Grenada' },
  kn: { de: 'St. Kitts & Nevis', en: 'St. Kitts & Nevis' },
  cu: { de: 'Kuba', en: 'Cuba' },
  do: { de: 'Dominik. Republik', en: 'Dominican Republic' },
  bb: { de: 'Barbados', en: 'Barbados' },
  ag: { de: 'Antigua & Barbuda', en: 'Antigua & Barbuda' },
  lc: { de: 'St. Lucia', en: 'St. Lucia' },
  vc: { de: 'St. Vincent', en: 'St. Vincent' },
  dm: { de: 'Dominica', en: 'Dominica' },
  bz: { de: 'Belize', en: 'Belize' },
  bs: { de: 'Bahamas', en: 'Bahamas' },
  bm: { de: 'Bermuda', en: 'Bermuda' },
  aw: { de: 'Aruba', en: 'Aruba' },
}

// Localized name for a team code; null if unknown (caller falls back).
export function countryName(code, lang) {
  const iso = CODE_TO_ISO[(code || '').toUpperCase()]
  const n = iso && NAMES[iso]
  return n ? n[lang] : null
}
