import { CODE_TO_ISO } from './flags'

// Localized country names keyed by flagcdn slug (ISO2 / UK nations).
const NAMES = {
  us: { de: 'USA', en: 'USA' },
  ca: { de: 'Kanada', en: 'Canada' },
  mx: { de: 'Mexiko', en: 'Mexico' },
  de: { de: 'Deutschland', en: 'Germany' },
  es: { de: 'Spanien', en: 'Spain' },
  fr: { de: 'Frankreich', en: 'France' },
  'gb-eng': { de: 'England', en: 'England' },
  'gb-sct': { de: 'Schottland', en: 'Scotland' },
  'gb-wls': { de: 'Wales', en: 'Wales' },
  pt: { de: 'Portugal', en: 'Portugal' },
  nl: { de: 'Niederlande', en: 'Netherlands' },
  it: { de: 'Italien', en: 'Italy' },
  be: { de: 'Belgien', en: 'Belgium' },
  hr: { de: 'Kroatien', en: 'Croatia' },
  ch: { de: 'Schweiz', en: 'Switzerland' },
  at: { de: 'Österreich', en: 'Austria' },
  dk: { de: 'Dänemark', en: 'Denmark' },
  pl: { de: 'Polen', en: 'Poland' },
  se: { de: 'Schweden', en: 'Sweden' },
  no: { de: 'Norwegen', en: 'Norway' },
  rs: { de: 'Serbien', en: 'Serbia' },
  tr: { de: 'Türkei', en: 'Türkiye' },
  ua: { de: 'Ukraine', en: 'Ukraine' },
  cz: { de: 'Tschechien', en: 'Czechia' },
  hu: { de: 'Ungarn', en: 'Hungary' },
  gr: { de: 'Griechenland', en: 'Greece' },
  si: { de: 'Slowenien', en: 'Slovenia' },
  sk: { de: 'Slowakei', en: 'Slovakia' },
  ro: { de: 'Rumänien', en: 'Romania' },
  br: { de: 'Brasilien', en: 'Brazil' },
  ar: { de: 'Argentinien', en: 'Argentina' },
  uy: { de: 'Uruguay', en: 'Uruguay' },
  co: { de: 'Kolumbien', en: 'Colombia' },
  ec: { de: 'Ecuador', en: 'Ecuador' },
  pe: { de: 'Peru', en: 'Peru' },
  cl: { de: 'Chile', en: 'Chile' },
  py: { de: 'Paraguay', en: 'Paraguay' },
  ve: { de: 'Venezuela', en: 'Venezuela' },
  bo: { de: 'Bolivien', en: 'Bolivia' },
  ma: { de: 'Marokko', en: 'Morocco' },
  sn: { de: 'Senegal', en: 'Senegal' },
  tn: { de: 'Tunesien', en: 'Tunisia' },
  dz: { de: 'Algerien', en: 'Algeria' },
  eg: { de: 'Ägypten', en: 'Egypt' },
  ng: { de: 'Nigeria', en: 'Nigeria' },
  cm: { de: 'Kamerun', en: 'Cameroon' },
  gh: { de: 'Ghana', en: 'Ghana' },
  ci: { de: 'Elfenbeinküste', en: 'Ivory Coast' },
  za: { de: 'Südafrika', en: 'South Africa' },
  ml: { de: 'Mali', en: 'Mali' },
  ao: { de: 'Angola', en: 'Angola' },
  cv: { de: 'Kap Verde', en: 'Cape Verde' },
  cd: { de: 'DR Kongo', en: 'DR Congo' },
  cg: { de: 'Kongo', en: 'Congo' },
  gn: { de: 'Guinea', en: 'Guinea' },
  jp: { de: 'Japan', en: 'Japan' },
  kr: { de: 'Südkorea', en: 'South Korea' },
  ir: { de: 'Iran', en: 'Iran' },
  sa: { de: 'Saudi-Arabien', en: 'Saudi Arabia' },
  au: { de: 'Australien', en: 'Australia' },
  qa: { de: 'Katar', en: 'Qatar' },
  iq: { de: 'Irak', en: 'Iraq' },
  ae: { de: 'VAE', en: 'UAE' },
  uz: { de: 'Usbekistan', en: 'Uzbekistan' },
  jo: { de: 'Jordanien', en: 'Jordan' },
  nz: { de: 'Neuseeland', en: 'New Zealand' },
  cr: { de: 'Costa Rica', en: 'Costa Rica' },
  pa: { de: 'Panama', en: 'Panama' },
  jm: { de: 'Jamaika', en: 'Jamaica' },
  hn: { de: 'Honduras', en: 'Honduras' },
  ht: { de: 'Haiti', en: 'Haiti' },
  cw: { de: 'Curaçao', en: 'Curaçao' },
  sv: { de: 'El Salvador', en: 'El Salvador' },
  gt: { de: 'Guatemala', en: 'Guatemala' },
}

// Localized name for a team code; null if unknown (caller falls back).
export function countryName(code, lang) {
  const iso = CODE_TO_ISO[(code || '').toUpperCase()]
  const n = iso && NAMES[iso]
  return n ? n[lang] : null
}
